### ISSUE TITLE
Mantenimiento del blog del proyecto.

### ISSUE THREAD

**Issue by renatolrr** [hugobarzano/NoInventory#11]
Tal como hemos hablado el blog del proyecto se monta en el dominio no-inventory.es ( a la espera de su activación en este momento)
También se procede a crear cuentas en redes sociales.

**Comment by hugobarzano** [comment]
El blog del proyecto esta activo y tambien se ha creado la siguiente cuenta de tweeter [@no_inventory](https://twitter.com/no_inventory)
