### ISSUE TITLE
Revisar licencia 

### ISSUE THREAD

**Issue by renatolrr** [hugobarzano/NoInventory#13]
Revisar

**Comment by hugobarzano** [comment]
Hola @psicobyte ¿podrias mirar la licencia que tengo? gracias

**Comment by psicobyte** [comment]
En principio, a menos que tenga alguna dependencia que yo no haya visto (He mirado los requisitos, el archivo install.sh, etc), la licencia es compatible con todo lo que usas y perfectamente correcta. close #13

**Comment by hugobarzano** [comment]
Gracias
