### ISSUE TITLE
Errores al compilar el PDF

### ISSUE THREAD

**Issue by JJ** [hugobarzano/NoInventory#33]
```
See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.12 ...idth=0.9\textwidth]{imagenes/logo_ugr.jpg}
                                                  \\[1.4cm]

```

**Comment by JJ** [comment]
De hecho, es que ni existe el directorio imagenes.

**Comment by hugobarzano** [comment]
Como bien me enseñaste en IV, al repositorio no se suben imagenes, ¿quieres que elimine del .gitignore la entrada correspondiente al directorio para que puedas compilarlo?

**Comment by hugobarzano** [comment]
Haz un "git pull" y prueba ahora @JJ

**Comment by JJ** [comment]
En este caso, si

El lunes, 27 de junio de 2016, hugobarzano notifications@github.com
escribió:

> Como bien me enseñaste en IV, al repositorio no se suben imagenes,
> ¿quieres que elimine del .gitignore la entrada correspondiente al
> directorio para que puedas compilarlo?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci3.googleusercontent.com/proxy/mHhKPDYSRTK4_yIf_qpl6iO36-UdI0nN-G0M6ehD569rwtW7icZkmhmA5qYvOx2eJPNp_N7CGW3qW0DIKyFRr-zfHbjgLfiJ65w40qjQkfEgePP2hXinhiHmhO9Z6q2mPIDAIvjLALUthkFZLjgFXgXsJum6EQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9BrXq6z1JgmdU0M4q5bQRa-3RngQks5qQBtqgaJpZM4I_Xma.gif

## 

JJ

**Comment by JJ** [comment]
Sigue sin estar este .jpg en particular, sigue dando el mismo error.

**Comment by hugobarzano** [comment]
Tenia otra entrada en el gitignore para las .jpg mis disculpas

**Comment by JJ** [comment]
Falta también la bibliografía. Y tiene errores de compilación en LaTeX. He corregido alguno.
