### ISSUE TITLE
Crear fichero log

### ISSUE THREAD

**Issue by renatolrr** [hugobarzano/NoInventory#9]
Como hemos hablado, nos va a permitir geolocalización.
Tambien restaurar.

**Comment by hugobarzano** [comment]
En lugar de utilizar fichero, he decidido utilizar la base de datos. La clase y el manejador correspondiente para el sistema de log estan en el archivo [log.py](https://github.com/hugobarzano/NoInventory/blob/master/NoInventory/log.py) cuando un usuario se registra con  una organizacion por primera vez, se crea un objeto de este tipo, comun a todos los miembros de la organizacion. que re registren despues. con el metodo registrarActividad(self,organizacion,mensaje) se van almacenando en forma de lista, cada unas de las aciones que se llevan acabo. En la vista de "preferencias" se tieene acceso al log de cada organizacion. Un saludo
